[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
booster_swap = "HdNeVJt9x8p5G5Q99A3PySR4bNnzaLzHdSAw5B5eWZzC"

[programs.devnet]
booster_swap = "HdNeVJt9x8p5G5Q99A3PySR4bNnzaLzHdSAw5B5eWZzC"


[registry]
url = "https://github.com/danielbui12/booster-swap"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pyth_oracle_get_price.test.ts"
exec = "yarn ts-node -r tsconfig-paths/register clients/swap.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
